#ifndef IOMap_h
#define IOMap_h
//#define robot_2
// CAN ID
#define CAN_ID_BREACHER_PIVOT 8
#define CAN_ID_BREACHER_BEATER_BAR 9
#define CAN_ID_SCALER_WINCH_A 10
#define CAN_ID_SCALER_WINCH_B 11
#define CAN_ID_SCALER_PIVOT 12

//PWM Out
#define PWM_OUT_DRIVE_LEFT 0
#define PWM_OUT_DRIVE_RIGHT 1
#define PWM_OUT_SCALER_WINCH_LOCK 4

//DIGITAL IO
#define DIG_IO_DRIVE_SHAFT_ENCODER_LEFT_A 0
#define DIG_IO_DRIVE_SHAFT_ENCODER_LEFT_B 1
#define DIG_IO_DRIVE_SHAFT_ENCODER_RIGHT_A 2
#define DIG_IO_DRIVE_SHAFT_ENCODER_RIGHT_B 3
#define DIG_IO_SCALER_WINCH_ENCODER_A 4
#define DIG_IO_SCALER_WINCH_ENCODER_B 5
#define DIG_IO_BREACHER_BEAM_BREAK 6
#define DIG_IO_BREACHER_UPPER_LIMIT 7
#define DIG_IO_BREACHER_LOWER_LIMIT 8
#define DIG_IO_GYRO_CALIBRATE 9

//ANALOG IN
#define ANALOG_IN_BREACHER_POT 1
#define ANALOG_IN_SCALER_PIVOT_POT 2
#define ANALOG_IN_DRIVE_GYRO 0
#endif
