// CAN ID
#define CAN_ID_BREACHER_PIVOT 8
#define CAN_ID_BREACHER_BEATER_BAR 9

//PWM Out
#define PWM_OUT_DRIVE_LEFT 0
#define PWM_OUT_DRIVE_RIGHT 1

//DIGITAL IO
#define DIG_IO_DRIVE_SHAFT_ENCODER_LEFT_A 0
#define DIG_IO_DRIVE_SHAFT_ENCODER_LEFT_B 1
#define DIG_IO_DRIVE_SHAFT_ENCODER_RIGHT_A 2
#define DIG_IO_DRIVE_SHAFT_ENCODER_RIGHT_B 3
#define DIG_IO_BREACHER_BEAM_BREAK 6
#define DIG_IO_BREACHER_UPPER_LIMIT 7
#define DIG_IO_BREACHER_LOWER_LIMIT 8

//ANALOG IN
#define ANALOG_IN_BREACHER_POT 1